image: "304756642807.dkr.ecr.ap-southeast-1.amazonaws.com/runner-image/kubernetes-deploy-tool"

stages:
  - package
  - publish


.deploy_job_template: &deploy_job_template
  before_script:
    - export COMPUTED_TAG="$(git describe --tags)"
  cache: {}

variables:
  HELM_CHART_STORE: s3://gofinance-helm-repo/charts
  AWS_ACCESS_KEY_ID: $CI_PIPELINE_IAM_ID
  AWS_SECRET_ACCESS_KEY: $CI_PIPELINE_IAM_SECRET
  AWS_REGION: ap-southeast-1
  CHART_NAME: loan-platform-backend-helm

package:
  <<: *deploy_job_template
  stage: package
  script:
  - helm init --client-only
  - helm package . --version $COMPUTED_TAG
  artifacts:
    paths:
    - ${CHART_NAME}*.tgz
    expire_in: 1 days
  tags:
    - loan-platform-docker-large

publish:
  stage: publish
  script:
  - helm init --client-only
  - helm repo add gofin ${HELM_CHART_STORE}
  - helm repo update
  - helm s3 push ./${CHART_NAME}*.tgz gofin
  tags:
    - loan-platform-docker-large
  only:
  - tags
