apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "application.name" . }}
  namespace: {{ .Values.deployment.namespace }}
  labels:
    release: {{ .Release.Name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  annotations:
{{- if .Values.configmap.annotations }}
{{ toYaml .Values.configmap.annotations | indent 4 }}
{{- end }}
data:
{{- if .Values.configmap.data }}
  {{- range $key, $value := .Values.configmap.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
